services:
  - type: redis
    name: sidekiq-redis
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: worker
    name: sidekiq-worker
    env: ruby
    region: frankfurt
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
